stages:
  - build-dev

build-dev:
  stage: build-dev
  # only:
  #   - dev
  tags:
    - debian
    - dss
  script:
    - docker build -t webx-sesman-builder .
    - docker create -ti --name webx-sesman-builder webx-sesman-builder bash
    - docker cp webx-sesman-builder:/app/target/debian/. .
    - docker rm -f webx-sesman-builder
    - PACKAGE_VERSION=`awk -F ' = ' '$1 ~ /version/ { gsub(/[\"]/, "", $2); printf("%s",$2) }' Cargo.toml`
    - cp webx-session-manager_${PACKAGE_VERSION}_amd64.deb webx-session-manager_dev_amd64.deb
  artifacts:
    paths:
      - webx-session-manager_dev_amd64.deb