[package]
name = "webx-session-manager"
version = "0.1.0"
edition = "2018"

[dependencies]
libc = "0.2.108"
rand = "0.8.4"
users = "0.11.0"
nix = "0.23.0"
pam-client = "0.3.1"
structopt = "0.3.25"
env_logger = "0.9.0"
log = "0.4.14"
zmq = "0.9.2"
ctrlc = "3.2.1"
