logging:
  # trace, debug, info or error
  level: debug
  # whether to log to console
  console: true
  # file logging configuration
  file:
    # whether to log to file
    enabled: true
    # path to the log file
    path: /var/log/webx/webx-session-manager.log
  # log message format
  format: "[{timestamp}][{level}] {message}"

transport:
  # path to the zmq ipc socket file. 
  # we recommend that you leave the default value
  ipc: /tmp/webx-session-manager.ipc

authentication:
  # the pam service to use for authenticating
  service: webx
  
xorg:
  # path to where the x lock files are stored
  lock_path: /tmp
  # path to where session files should be stored
  # for example the XAuthority for a session will be stored here
  sessions_path: /run/webx/sessions
  # path for the xorg configuration
  config_path: /etc/X11/xrdp/xorg.conf
  # ext available display will start from this offset
  display_offset: 60
  # script to launch the window manager of your choice
  window_manager: /etc/webx/webx-session-manager/startwm.sh
  log_path: /var/log/webx/session-manager/sessions
  